# Generated by Django 5.2 on 2025-05-04 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, unique=True)),
                ('grade', models.IntegerField()),
                ('is_active', models.BooleanField()),
                ('avatar', models.ImageField(upload_to='avatars/')),
            ],
            options={
                'db_table': 'students',
            },
        ),
    ]
